// voting-svelte/src/Votings.svelte
<script>
    import VotingCard from './VotingCard.svelte'
    import VotingForm from './VotingForm.svelte'
    import { createVotings } from './store/votings.js'

    let state = 'listing'
    let current = null

    let votings = createVotings()
    
    function newVoting() {
        votings.createVoting()
        current = $votings.length-1
        state = 'new'
    }

    function editVoting(index) {
        current = index
        state = 'edit'
    }

    function removeVoting(index) {
        votings.deleteVoting(index)
    }

    function openVoting(index) {
        current = index
        state = 'open'
    }

    function updateChanges(voting) {
        votings.updateVoting(voting.detail,current)
        state = 'listing'
    }

    function cancelChanges() {
        if (state === 'new') votings.deleteVoting($votings.length-1)
        state = 'listing'
    }

    function goBack() {
        state = 'listing'
    }
</script>

<main>
    {#if state === 'open'}
        <div>
            <VotingCard title={$votings[current].title} 
                state={$votings[current].state} 
                votes={$votings[current].votes} 
            />
            <button on:click={goBack}>Voltar</button>
        </div>
    {:else if state === 'new' || state === 'edit'}
        <div>
            <h1>Formulário de votação</h1>
            <VotingForm 
                voting={$votings[current]}
                on:canceled={cancelChanges}
                on:updated={updateChanges}
            />
        </div>
    {:else if state === 'listing'}
        <div>
            <h1>Votações</h1>
            <p><button on:click={newVoting}>Nova votação</button></p>
            {#each $votings as voting,index}
                <p class="vote">
                { voting.title }
                {#each voting.votes as option}
                    <span class="option">
                        { option.option } ({ option.count })
                    </span>
                {/each}
            
                <br/>
                <button class="listing" on:click={event => editVoting(index)}>Editar</button>
                <button class="listing" on:click={event => removeVoting(index)}>Remover</button>
                <button class="listing" on:click={event => openVoting(index)}>Abrir</button>
                </p>
            {/each}
        </div>
    {/if}
</main>

// voting-angular/src/app/votings/votings.component.ts
import { Component, Input } from '@angular/core'
import { VotingsService } from '../votings.service'

@Component({
    selector: 'votings',
    templateUrl: './votings.component.html'
})

export class VotingsComponent {
    state = 'listing'
    current = null

    constructor(public votingsService : VotingsService) { /* empty */ }

    newVoting() {
        this.votingsService.createVoting()
        this.current = this.votingsService.votings.length-1
        this.state = 'new'
    }

    editVoting(index) {
        this.current = index
        this.state = 'edit'
    }

    removeVoting(index) {
        this.votingsService.deleteVoting(index)
    }

    openVoting(index) {
        this.current = index
        this.state = 'open'
    }

    updateChanges(voting) {
        this.votingsService.updateVoting(voting,this.current)
        this.state = 'listing'
    }

    cancelChanges() {
        if (this.state === 'new') this.votingsService.deleteVoting(this.votingsService.votings.length-1)
        this.state = 'listing'
    }

    goBack() {
        this.state = 'listing'
    }
}
<div *ngIf="state === 'open'">
    <voting-card 
        [title]='votingsService.votings[current].title'
        [state]='votingsService.votings[current].state'
        [votes]='votingsService.votings[current].votes'
    ></voting-card>
    <button (click)='goBack()'>Voltar</button>
</div>

<div *ngIf="state === 'new' || state === 'edit'">
    <h1>Formulário de votação</h1>
    <voting-form
        [voting]="votingsService.votings[current]"
        (updated)="updateChanges($event)"
        (canceled)="cancelChanges($event)"
    ></voting-form>
</div>

<div *ngIf="state === 'listing'">
    <h1>Votações</h1>
    <p><button (click)="newVoting()">Nova votação</button></p>
    <p class='vote' *ngFor='let voting of votingsService.votings; index as i'>
        {{ voting.title }}
        <span class='option' *ngFor='let option of voting.votes, index as i'>
            {{ option.option }} ({{ option.count }})
        </span>
        <br/>
        <button class='listing' (click)="editVoting(i)">Editar</button>
        <button class='listing' (click)="removeVoting(i)">Remover</button>
        <button class='listing' (click)="openVoting(i)">Abrir</button>
    </p>
</div>
