// voting-vue/src/components/Votings.vue
<template>
  <div v-if="state === 'open'">
    <VotingCard :title="votings[current].title" :state="votings[current].state" :votes="votings[current].votes" />
    <button @click="goBack()">Voltar</button>
  </div>
  <div v-else-if="state === 'new' || state === 'edit'">
    <h1>Formulário de votação</h1>
    <VotingForm 
      :voting="votings[current]" 
      @canceled="cancelChanges"
      @updated="updateChanges"
    />
  </div>
  <div v-else-if="state === 'listing'">
    <h1>Votações</h1>
    <p><button @click="newVoting()">Nova votação</button></p>
    <p class="vote" v-for="(voting, index) in votings" :key="index">
      {{ voting.title }}
      <span class="option" v-for="(option, index) in voting.votes" :key="index">
        {{ option.option }} ({{ option.count }})
      </span>
      <br />
      <button class="listing" @click="editVoting(index)">Editar</button>
      <button class="listing" @click="removeVoting(index)">Remover</button>
      <button class="listing" @click="openVoting(index)">Abrir</button>
    </p>
  </div>
</template>

<script>
import { ref } from "vue"
import VotingCard from "./VotingCard.vue"
import VotingForm from "./VotingForm.vue"

import {
  votings,
  createVoting,
  updateVoting,
  deleteVoting,
} from "../api/votings"

export default {
  components: {
    VotingCard,
    VotingForm
  },
  setup: () => {
    const state = ref("listing")
    const current = ref(0)
    
    const newVoting = () => {
      createVoting()
      current.value = votings.length - 1
      state.value = "new"
    }
    const editVoting = (index) => {
      current.value = index
      state.value = "edit"
    }
    const removeVoting = (index) => {
      deleteVoting(index)
    }
    const openVoting = (index) => {
      current.value = index
      state.value = "open"
    }
    const updateChanges = (voting) => {
      updateVoting(voting, current.value)
      state.value = "listing"
    }
    const cancelChanges = () => {
      if (state.value === "new") deleteVoting(votings.length - 1)
      state.value = "listing"
    }
    const goBack = () => { state.value = "listing" }

    return {
      votings,
      state,
      current,
      newVoting,
      editVoting,
      removeVoting,
      openVoting,
      updateVoting,
      updateChanges,
      cancelChanges,
      goBack
    }
  },
}
</script>

// voting-react/src/components/Votings.js
import React, { useState } from 'react'
import VotingsData from '../hooks/votings-hook'
import VotingCard from './VotingCard'
import VotingForm from './VotingForm'

export default function Votings() {

    const [state,setState] = useState('listing')
    const [current,setCurrent] = useState(null)

    const {votings,createVoting,updateVoting,deleteVoting} = VotingsData()

    function newVoting() {
        createVoting()
        setCurrent(votings.length)
        setState('new')
    }

    function editVoting(index) {
        setCurrent(index)
        setState('edit')
    }

    function removeVoting(index) {
        deleteVoting(index)
    }

    function openVoting(index) {
        setCurrent(index)
        setState('open')
    }

    function updateChanges(voting) {
        updateVoting(voting,current)
        setState('listing')
    }

    function cancelChanges() {
        if (state === 'new') deleteVoting(votings.length-1)
        setState('listing')
    }

    function goBack() {
        setState('listing')
    }

    let content

    if (state === 'open') {
        content = (
            <VotingCard 
                title={votings[current].title} 
                state={votings[current].state}
                votes={votings[current].votes}
            />
        )

        return (
            <div>
                {content}
                <button onClick={() => goBack()}>Voltar</button>
            </div>
        )
    } else if (state === 'new' || state === 'edit') {
        content = ( 
            <VotingForm 
                onUpdate={(voting) => updateChanges(voting)}
                onCancel={() => cancelChanges()}
                voting={votings[current]}
            />
        )
        return (
            <div>
                <h1>Formulário de votação</h1>
                {content}
            </div>
        );

    } else { // listing
        let list = votings.map((item,index) => 
            <p class='vote' key={index+item.title}>
                {item.title}
                {item.votes.map((item,index) =>
                    <span class='option' key={index}>{item.option} ({item.count})</span>
                )}
                <br/>
                <button class='listing' onClick={() => editVoting(index)}>Editar</button>
                <button class='listing' onClick={() => removeVoting(index)}>Remover</button>
                <button class='listing' onClick={() => openVoting(index)}>Abrir</button>
            </p>
        )

        content = (
            <div>
                <p><button class='new' onClick={() => newVoting()}>Nova votação</button></p>
                {list}
            </div>
        )

        return (
            <div>
                <h1>Votações</h1>
                {content}
            </div>
        );
    }
}
