// voting-svelte/src/VotingForm.svelte
<script>
    import { createEventDispatcher } from 'svelte'
    import * as yup from 'yup'

    import Input from './Input.svelte'

    export let voting
    const dispatcher = createEventDispatcher()
    
    let data = {
            title: voting.title || '',
            option1: 
                voting.votes.length > 0 ? voting.votes[0]['option'] : '',
            option2: 
                voting.votes.length > 1 ? voting.votes[1]['option'] : '',
            option3: 
                voting.votes.length > 2 ? voting.votes[2]['option'] : '',
            option4: 
                voting.votes.length > 3 ? voting.votes[3]['option'] : '',
        }
    let errors = {}

    const schema = yup.object().shape({
            title: yup.string()
                .test('len', 'Título deve ter pelo menos 5 caracteres', val => val.length >= 5)
                .required("Título é obrigatório"),
            option1: yup.string()
                .test('len', 'Opção 1 deve ter pelo menos 2 caracteres', val => val.length >= 2)
                .required("Opção 1 é obrigatória"),
            option2: yup.string()
                .test('len', 'Opção 2 deve ter pelo menos 2 caracteres', val => val.length >= 2)
                .required("Opção 2 é obrigatória"),
            option3: yup.string()
                .test('len', 'Opção 3 deve ter pelo menos 2 caracteres', val => val.length == 0 || val.length >= 2),
            option4: yup.string()
                .test('len', 'Opção 4 deve ter pelo menos 2 caracteres', val => val.length == 0 || val.length >= 2)
        })

    function extractErrors ({inner}) {
        return inner.reduce((acc, err) => {
            return { ...acc, [err.path]: err.message }
        }, {})
    }

    function validate(err) {
        schema
            .validate(data, { abortEarly: false })
            .then(() => errors = {})
            .catch(err => errors = extractErrors(err))
    }

    function onSubmit() {
        schema
            .validate(data, { abortEarly: false })
            .then(() => {
                dispatcher('updated', {
                title: data.title,
                state: voting.state,
                votes: [data.option1,data.option2,data.option3,data.option4]
                            .map(element => { return {option:element,count:0}})
                            .filter(element => element.option.trim() !== '')
        })
            })
            .catch(err => {
                errors = extractErrors(err)
            })
    }

</script>

<main>
    <form on:submit|preventDefault={onSubmit}>
        <Input label="Título"
            placeholder="Insira o título"
            isRequired="true"
            bind:error={errors.title}
            bind:value={data.title}
            on:validate={validate}
        />
        <Input label="Opção 1"
            placeholder="Insira a opção 1"
            isRequired="true"
            bind:error={errors.option1}
            bind:value={data.option1}
            on:validate={validate}
        />
        <Input label="Opção 2"
            placeholder="Insira a opção 2"
            isRequired="true"
            bind:error={errors.option2}
            bind:value={data.option2}
            on:validate={validate}
        />
        <Input label="Opção 3"
            placeholder="Insira a opção 3"
            bind:error={errors.option3}
            bind:value={data.option3}
            on:validate={validate}
        />
        <Input label="Opção 4"
            placeholder="Insira a opção 4"
            bind:error={errors.option4}
            bind:value={data.option4}
            on:validate={validate}
        />

        <button type="submit">Enviar</button>
        <button on:click={event => dispatcher('canceled')} type="button">Cancelar</button>
    </form>
</main>

// voting-angular/src/app/voting-form/voting-form.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core'
import * as yup from 'yup'

interface VotingType {
    title: string
    state: boolean
    votes: []
  }

@Component({
    selector: 'voting-form',
    templateUrl: './voting-form.component.html'
})

export class VotingFormComponent implements OnInit {
    @Input() voting: VotingType
    
    @Output() canceled = new EventEmitter()
    @Output() updated = new EventEmitter()

    data
    errors

    schema = yup.object().shape({
        title: yup.string()
            .test('len', 'Título deve ter pelo menos 5 caracteres', val => val.length >= 5)
            .required("Título é obrigatório"),
        option1: yup.string()
            .test('len', 'Opção 1 deve ter pelo menos 2 caracteres', val => val.length >= 2)
            .required("Opção 1 é obrigatória"),
        option2: yup.string()
            .test('len', 'Opção 2 deve ter pelo menos 2 caracteres', val => val.length >= 2)
            .required("Opção 2 é obrigatória"),
        option3: yup.string()
            .test('len', 'Opção 3 deve ter pelo menos 2 caracteres', val => val.length == 0 || val.length >= 2),
        option4: yup.string()
            .test('len', 'Opção 4 deve ter pelo menos 2 caracteres', val => val.length == 0 || val.length >= 2)
    })

    extractErrors ({inner}) {
        return inner.reduce((acc, err) => {
            return { ...acc, [err.path]: err.message }
        }, {})
    }

    validate() {
        this.schema
            .validate(this.data, { abortEarly: false })
            .then(() => this.errors = {})
            .catch(err => this.errors = this.extractErrors(err))
    }
    
    ngOnInit() {
        this.data = {}
        this.errors = {}
        this.data.title = this.voting.title || ''
        const options = ['','','','']
        this.voting.votes.forEach((value,index) => options[index] = value['option'])
        this.data.option1 = options[0]
        this.data.option2 = options[1]
        this.data.option3 = options[2]
        this.data.option4 = options[3]
    }

    onSubmit() {
        this.schema
            .validate(this.data, { abortEarly: false })
            .then(() => {
                let tempVotes = [
                    this.data.option1,
                    this.data.option2,
                    this.data.option3,
                    this.data.option4
                ].map(
                    (option) => { 
                        return {option:option,count:0}
                    }).filter(
                        (item) => item.option.trim() !== ''
                    )
            
                this.updated.emit(
                    {
                        title:this.data.title,
                        state:this.voting.state,
                        votes:tempVotes
                    }
                )
            }).catch(err => {
                this.errors = this.extractErrors(err)
            })
    }
}
<div>
    <form #votingForm="ngForm" (ngSubmit)="votingForm.form.valid && onSubmit()">
        <custom-input
            label="Título"
            name="title"
            placeholder="Insira o título da votação"
            [(value)]="data.title"
            isRequired="true"
            minlength=3
            (valueChange)="validate()"
            [(error)]="errors.title"
        ></custom-input>

        <custom-input
            label="Opção 1"
            placeholder="Insira a opção 1"
            [(value)]="data.option1"
            isRequired="true"
            (valueChange)="validate()"
            [(error)]="errors.option1"
        ></custom-input>

        <custom-input
            label="Opção 2"
            placeholder="Insira a opção 2"
            [(value)]="data.option2"
            isRequired="true"
            (valueChange)="validate()"
            [(error)]="errors.option2"
        ></custom-input>

        <custom-input
            label="Opção 3"
            placeholder="Insira a opção 3"
            [(value)]="data.option3"
            (valueChange)="validate()"
            [(error)]="errors.option3"
        ></custom-input>

        <custom-input
            label="Opção 4"
            placeholder="Insira a opção 4"
            [(value)]="data.option4"
            (valueChange)="validate()"
            [(error)]="errors.option4"
        ></custom-input>

        <button type='submit'>Enviar</button>
        <button (click)="canceled.emit()">Cancelar</button>
    </form>
</div>
