// quiz-vue/src/components/VotingCard.vue
<template>
  <div
    class="vote card"
    :class="{ 'vote result': this.quizState === 'closed' }"
  >
    <h3>
      <b>{{ title }}</b>
    </h3>
    <div v-if="this.quizState === 'open'">
      <VotingBooth :options="quizOptions" @onVote="vote" />
    </div>
    <div v-else-if="this.quizState === 'closed'">
      <VotingResult :votes="quizOptions" />
    </div>
    <div v-else>
      <p>[wrong state] {{ quizState }}</p>
    </div>
  </div>
</template>

<script>
import VotingBooth from "./VotingBooth.vue";
import VotingResult from "./VotingResult.vue";

export default {
  props: {
    title: String,
    state: String,
    votes: Array,
  },
  components: { VotingBooth, VotingResult },
  data: (props) => ({
    quizState: props.state,
    quizOptions: props.votes,
  }),
  methods: {
    vote(voteIndex) {
      this.quizOptions[voteIndex]["count"] =
        this.quizOptions[voteIndex]["count"] + 1;
      this.quizState = "closed";
    },
  },
};
</script>

// quiz-react/src/components/VotingCard.js
/* O card de votação: recebe como parâmetro (props) um título, o estado ("open" ou "closed") 
 * e um array com as opções contendo o texto e o número de votos atuais.
 */

import React, { useState } from 'react'
import VotingBooth from './VotingBooth'
import VotingResult from './VotingResult'

export default function VotingCard({title, state, votes, ...props}) {
    
    const [quizState,setQuizState] = useState(state)
    const [quizOptions,setQuizOptions] = useState(votes)

    const options = votes.map(item => item.option)

    function vote(voteIndex) {
        quizOptions[voteIndex]['count'] = quizOptions[voteIndex]['count'] + 1
        setQuizState('closed')
        setQuizOptions(quizOptions)
    }

    let content

    console.log(quizState)
    if (quizState === 'open') {
        content = (
            <VotingBooth options={options} onVote={vote} />
        )
    } else if (quizState === 'closed') {
        content = (
            <VotingResult votes={quizOptions} />
        )
    } else {
        content = (
            <p>[wrong state] {quizState}</p>
        )
    }

    return (
        <div className={quizState === 'open' ? 'vote card' : 'vote result'}>
            <h3><b>{title}</b></h3>
            {content}
        </div>
    )
}
