// voting-svelte/src/Input.svelte
<script>
    import { createEventDispatcher } from 'svelte'

    export let value = ''
    export let label = ''
    export let placeholder = ''
    export let isRequired = false
    export let error = ''

    const dispatcher = createEventDispatcher()
</script>

<main>
    <div class="form-item">
        <!-- svelte-ignore a11y-label-has-associated-control -->
        <label class="label">
            { label }{#if isRequired}<span style="color: red">*</span>{/if}
        </label>
        <div>
            <input
                type="text"
                placeholder={placeholder}
                bind:value={value}
                on:input={event => dispatcher('validate')}
                on:blur={event => dispatcher('validate')}
                on:change={event => dispatcher('validate')}
            />
            {#if error}
                <div class="error">{ error }</div>
            {/if}
        </div>
    </div>
</main>

// voting-vue/src/components/Input.vue
<template>
  <div class="form-item">
    <label class="label">
      {{ label }}<span v-if="isRequired" style="color: red">*</span>
    </label>
    <div>
      <input
        type="text"
        :placeholder="placeholder"
        :value="modelValue"
        @change="$emit('update:modelValue', $event.target.value)"
        @blur="$emit('validate', name)"
      />
      <div class="error">{{ error }}</div>
    </div>
  </div>
</template>

<script>
export default {
  props: [
    'label',
    'name',
    'placeholder',
    'isRequired',
    'touched',
    'error',
    'modelValue'
  ]
}
</script>
