// voting-angular/src/app/input/input.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core'
import { NgModel } from '@angular/forms'

@Component({
    selector: 'custom-input',
    templateUrl: './input.component.html'
})

export class InputComponent {
    @Input() label: string
    @Input() name: string
    @Input() value: string
    @Input() placeholder: string
    @Input() isRequired: boolean
    @Input() minlength?: number

    @Output() changed = new EventEmitter<string>()

    error(elm: NgModel) {
        if (elm.invalid && elm.touched) {
            if (elm.errors.required) return 'Campo obrigatório'
            if (elm.errors.minlength)
                return this.label + ' deve ter pelo menos ' + this.minlength + ' caracteres'
        }
    }
}
<div class="form-item">
    <label class="label">
        {{ label }}
        <span *ngIf="isRequired" style="color: 'red'">*</span>
    </label>

    <div>
        <input
            #inputField="ngModel"
            type="text"
            [name]="name"
            [placeholder]="placeholder"
            [required]="isRequired"
            [(ngModel)]="value"
            (change)="changed.emit(inputField.value)"
            (blur)="changed.emit(inputField.value)"
            [minlength]="minlength"
        />
        
        <div class="error">{{ error(inputField) }}</div>
    </div>
</div>

// voting-vue/src/components/Input.vue
<template>
  <div class="form-item">
    <label>
      {{ label }}
      <span v-if="isRequired" style="color: red">*</span>
    </label>
    <div>
      <input
        type="text"
        :placeholder="placeholder"
        :value="modelValue"
        @change="$emit('update:modelValue', $event.target.value)"
        @blur="$emit('blur', name)"
      />
      <div class="error">{{ error }}</div>
    </div>
  </div>
</template>

<script>
export default {
  props: [
    'label',
    'name',
    'placeholder',
    'isRequired',
    'touched',
    'error',
    'modelValue'
  ]
}
</script>
