// voting-react/src/components/VotingForm.js
import React, { useState } from 'react'
import { Formik } from 'formik'
import Input from './Input'

export default function VotingForm({voting,onUpdate,onCancel,props}) {

    const [currVoting,setCurrVoting] = useState(voting)

    console.log(currVoting)

    return (
        <div>
            <Formik
            enableReinitialize={true}
            initialValues={{
                title: voting.title || '',
                option1: 
                    (voting.votes.length > 0) 
                        ? voting.votes[0].option
                        : '',
                option2: 
                    (voting.votes.length > 1) 
                        ? voting.votes[1].option
                        : '',
                option3: 
                    (voting.votes.length > 2) 
                        ? voting.votes[2].option
                        : '',
                option4: 
                    (voting.votes.length > 3) 
                        ? voting.votes[3].option
                        : '',
            }}
            validate={values => {
                const errors = {};
                if (!values.title) errors.title = 'Título é obrigatório'
                else if (values.title.length < 5) errors.title = 'Título inválido'

                if (!values.option1) errors.option1 = 'Campo obrigatório'
                if (!values.option2) errors.option2 = 'Campo obrigatório'

                return errors
            }}
            onSubmit={(values, { setSubmitting }) => {
                const options = [{option:values.option1,count:0},
                                {option:values.option2,count:0},
                                {option:values.option3,count:0},
                                {option:values.option4,count:0}
                            ].filter((item) => item.option.trim() !== '')
                
                voting.title = values.title
                voting.votes = options
                onUpdate(voting)
            }}
            >
            {({
                values,
                errors,
                touched,
                handleChange,
                handleBlur,
                handleSubmit,
                isSubmitting,
            }) => (
                <form onSubmit={handleSubmit}>
                <Input
                    label='Título'
                    name='title'
                    placeholder='Insira o título da votação'
                    value={values.title}
                    onChange={handleChange}
                    onBlur={handleBlur}
                    isRequired={true}
                    errors={errors}
                    touched={touched}
                />
                
                <Input
                    label='Opção 1'
                    name='option1'
                    placeholder='Insira a opção 1'
                    value={values.option1}
                    onChange={handleChange}
                    onBlur={handleBlur}
                    isRequired={true}
                    errors={errors}
                    touched={touched}
                />

                <Input
                    label='Opção 2'
                    name='option2'
                    placeholder='Insira a opção 2'
                    value={values.option2}
                    onChange={handleChange}
                    onBlur={handleBlur}
                    isRequired={true}
                    errors={errors}
                    touched={touched}
                />

                <Input
                    label='Opção 3'
                    name='option3'
                    placeholder='Insira a opção 3'
                    value={values.option3}
                    onChange={handleChange}
                    onBlur={handleBlur}
                    isRequired={false}
                    errors={errors}
                    touched={touched}
                />

                <Input
                    label='Opção 4'
                    name='option4'
                    placeholder='Insira a opção 4'
                    value={values.option4}
                    onChange={handleChange}
                    onBlur={handleBlur}
                    isRequired={false}
                    errors={errors}
                    touched={touched}
                />
                
                <button type='submit' disabled={isSubmitting}>Enviar</button>
                <button onClick={() => onCancel()}>Cancelar</button>
                </form>
            )}
            </Formik>
        </div>
    );
}

// voting-vue/src/components/VotingForm.vue
<template>
    <form @submit.prevent="onSubmit">
        <Input
          label="Título"
          v-model="data.title"
          placeholder="Insira o título"
          isRequired="true"
          :error="errors['title']"
          @input="touched['title'] = true"
          @validate="validate('title','Título')"
        />
        
        <Input
          label="Opção 1"
          v-model="data.options[0]"
          placeholder="Insira a opção 1"
          isRequired="true"
          :error="errors['option1']"
          @input="touched['option1'] = true"
          @validate="validate('option1','Opção 1')"
        />

        <Input
          label="Opção 2"
          v-model="data.options[1]"
          placeholder="Insira a opção 2"
          isRequired="true"
          :error="errors['option2']"
          @input="touched['option2'] = true"
          @validate="validate('option2','Opção 2')"
        />

        <Input
          label="Opção 3"
          v-model="data.options[2]"
          placeholder="Insira a opção 3"
          :error="errors['option3']"
          @input="touched['option3'] = true"
          @validate="validate('option3','Opção 3')"
        />

        <Input
          label="Opção 4"
          v-model="data.options[3]"
          placeholder="Insira a opção 4"
          :error="errors['option4']"
          @input="touched['option4'] = true"
          @validate="validate('option4','Opção 4')"
        />
        
        <button type="submit">Enviar</button>
        <button @click="$emit('canceled')" type="button">Cancelar</button>
    </form>
</template>

<script>

import { reactive } from 'vue'

import Input from './Input.vue'
import { minLength, required } from '../form/validation'

export default {
  components: { 
    Input 
  },
  props: ['voting'],
  setup: (props) => {
    const data = {title: props.voting.title || '',options:['','','','']}
    props.voting.votes.forEach((element,index) => {
      data.options[index] = element.option
    })
    
    const errors = reactive({})
    const touched = reactive({})
    
    function onSubmit() {
      const labels = {
       'title':'Título',
       'option1':'Opção 1',
       'option2':'Opção 2',
       'option3':'Opção 3',
       'option4':'Opção 4'
      };

      ['title','option1','option2','option3','option4'].filter(input => {
        this.touched[input] = true
        this.validate(input,labels[input])
        return errors[input] == null ? 0 : 1
      })

      const valid = !Object.values(this.errors).some((value) => value)
      console.log(errors)
      if(valid) {
        const tempVoting = {
          title: this.data.title,
          state: props.voting.state,
          votes: this.data.options.map(
            (option) => { 
                return {option:option,count:0}
            }).filter(
                (item) => item.option.trim() !== ''
            )
        }
        this.$emit('updated',tempVoting)
      } 
    }

    function validate(name,label) {
      if (name == 'title') {
        const error = required(label,this.data.title) || 
                      minLength(label,5,this.data.title)
        errors[name] = this.touched[name] ? error : null
      } else {
        const tempMap = {
          'option1':this.data.options[0],
          'option2':this.data.options[1],
          'option3':this.data.options[2],
          'option4':this.data.options[3]
        }

        if (name == 'option1' || name == 'option2') {
          const error = required(label,tempMap[name]) 
                        || minLength(label,2,tempMap[name])
          errors[name] = this.touched[name] ? error : null
        } else {
          const error = minLength(label,2,tempMap[name])
          errors[name] = this.touched[name] ? error : null
        } 
      }
    }

    return {
      data,
      errors,
      touched,
      onSubmit,
      validate
    }
  },
}
</script>
