// voting-svelte/src/App.svelte
<script>
	import './app.css'
	import VotingCard from './VotingCard.svelte'

	let title = 'Pink Floyd é a melhor banda de Rock britânica?'
    let votes = [{ option: 'Sim', count: 10 },{ option: 'Não', count: 2 }]
	let state = 'open'
</script>

<main>
	<div>
		<VotingCard title={ title } votes={ votes } state={ state } />
	</div>
</main>

<style>

</style>

// voting-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <div>
      <voting-card 
        [title]="title" 
        [state]="state"
        [votes]="votes"
      ></voting-card>
    </div>
  `
})

export class AppComponent {
  title = 'Pink Floyd é a melhor banda de Rock britânica?'
  state = 'open'
  votes = [{'option':'Sim','count':10},{'option':'Não','count':2}]
}
