// quiz-svelte/src/VotingCard.svelte
<script>
    import VotingResult from './VotingResult.svelte'
    import VotingBooth from './VotingBooth.svelte'
    
    export let title
    export let state
    export let votes

    function vote(event) {
        let voteIndex = event.detail.voteIndex
        votes[voteIndex].count = votes[voteIndex].count + 1
        state = 'closed'
    }
</script>

<div class="vote card" class:result="{state === 'closed'}">
    <h3><b>{ title }</b></h3>
    {#if state === 'open'}
        <VotingBooth votes={ votes } on:voted={vote} />
    {:else if state === 'closed'}
        <VotingResult options={ votes } />
    {:else}
        <p>[wrong state] { state }</p>
    {/if}
</div>

// voting-angular/src/app/voting-card/voting-card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'voting-card',
  templateUrl: './voting-card.component.html'
})

export class VotingCardComponent {
  @Input() title: string
  @Input() state: string
  @Input() votes: {}[]
  constructor() { }

  vote(voteIndex: number) {
    this.votes[voteIndex]['count'] = this.votes[voteIndex]['count'] + 1
    this.state = 'closed'
  }
}
