// voting-vue/src/App.vue
<template>
  <div id="app">
    <VotingCard :title="this.title" :state="'open'" :votes="this.votes" />
    <Votings />
  </div>
</template>

<script>
import VotingCard from "./components/VotingCard.vue";
import Votings from "./components/Votings.vue";

export default {
  name: "App",
  components: {
    VotingCard,
    Votings
  },
  data: () => ({
    title: "Pink Floyd é a melhor banda de Rock britânica?",
    votes: [
      { option: "Sim", count: 10 },
      { option: "Não", count: 2 },
    ],
  }),
};
</script>

<style>
@import "./App.css";
</style>

// voting-svelte/src/App.svelte
<script>
	import './app.css'
	import VotingCard from './VotingCard.svelte'

	let title = 'Pink Floyd é a melhor banda de Rock britânica?'
    let votes = [{ option: 'Sim', count: 10 },{ option: 'Não', count: 2 }]
	let state = 'open'
</script>

<main>
	<div>
		<VotingCard title={ title } votes={ votes } state={ state } />
	</div>
</main>

<style>

</style>
