// voting-svelte/src/VotingResult.svelte
<script>
    export let votes

    function perc(index) {
        let total = votes.reduce((sum, item) => {return sum + item.count}, 0)
        return (votes[index].count/total*100).toFixed(2)
    }
</script>

<div>
    <ol>
        {#each votes as item, index (item)}
            <li>
                {item.option}: {item.count} votes ({perc(index)}%)
            </li>
        {/each}
    </ol>
</div>

// quiz-angular/src/app/voting-result/voting-result.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'voting-result',
  templateUrl: './voting-result.component.html'
})

export class VotingResultComponent {
  @Input() votes: []
  constructor() { }

  perc(index: number) {
    let total = this.votes.reduce((sum, item) => {return sum + item['count']}, 0)
    return (this.votes[index]['count']/total*100).toFixed(2)       
  }
}

<div>
  <ol>
    <li
			*ngFor="let item of votes; index as index"
    >
			{{ item.option }}: {{ item.count }} votes ({{ perc(index) }}%)
    </li>
	</ol>
</div>
